steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - 'gcloud'
  - 'functions'
  - 'deploy'
  - 'make_daily_report' 
  - '--gen2'
  - '--region=us-central1'
  - '--runtime=python311'
  - '--source=.'
  - '--entry-point=make_daily_report'
  - '--trigger-http'
  - '--no-allow-unauthenticated'
  - '--service-account=studyfellow@appspot.gserviceaccount.com'
  - '--memory=512MB'
  timeout: '1200s'

options:
  logging: CLOUD_LOGGING_ONLY